#FROM golang:1.23-alpine
#LABEL authors="DJ Tape"
#
#WORKDIR /app
#
#COPY ./../go.mod ./../go.sum ./
#RUN go mod download
#
#COPY . ./
#
#RUN go build ./cmd/app/main.go -o main
#
#EXPOSE 8080
#
#CMD ["./main"]
#
##ENTRYPOINT ["top", "-b"]